var url = '.';

export const TRAITS_MAP: any = {
  "face": {
    "common": [
      url + '/traits/face/common/1.png',
      url + '/traits/face/common/2.png',
      url + '/traits/face/common/3.png',
      url + '/traits/face/common/4.png',
      url + '/traits/face/common/5.png',
      url + '/traits/face/common/6.png',
      url + '/traits/face/common/7.png',
      url + '/traits/face/common/8.png',
      url + '/traits/face/common/9.png',
      url + '/traits/face/common/10.png',
      url + '/traits/face/common/11.png',
      url + '/traits/face/common/12.png',
      url + '/traits/face/common/13.png',
      url + '/traits/face/common/14.png',
      url + '/traits/face/common/15.png',
      url + '/traits/face/common/16.png',
      url + '/traits/face/common/17.png',
      url + '/traits/face/common/18.png',
      url + '/traits/face/common/19.png',
      url + '/traits/face/common/20.png',
      url + '/traits/face/common/21.png',
    ],
    "uncommon": [
      url + '/traits/face/uncommon/22.png',
      url + '/traits/face/uncommon/23.png',
      url + '/traits/face/uncommon/24.png',
      url + '/traits/face/uncommon/25.png',
      url + '/traits/face/uncommon/26.png',
      url + '/traits/face/uncommon/27.png',
      url + '/traits/face/uncommon/28.png',
      url + '/traits/face/uncommon/29.png',
      url + '/traits/face/uncommon/30.png',
      url + '/traits/face/uncommon/31.png',
      url + '/traits/face/uncommon/32.png',
    ],
    "rare": [
      url + '/traits/face/rare/33.png',
      url + '/traits/face/rare/34.png',
      url + '/traits/face/rare/35.png',
      url + '/traits/face/rare/36.png',
      url + '/traits/face/rare/37.png',
      url + '/traits/face/rare/38.png',
    ],
    "superrare": [
      url + '/traits/face/superrare/39.png',
      url + '/traits/face/superrare/40.png',
      url + '/traits/face/superrare/41.png',
      url + '/traits/face/superrare/42.png',
    ],
    "mythic": [
      url + '/traits/face/mythic/43.png',
      url + '/traits/face/mythic/44.png',
    ],
  },
  "cloths": {
    "common": [
      url + '/traits/cloths/common/1.png',
      url + '/traits/cloths/common/2.png',
      url + '/traits/cloths/common/3.png',
      url + '/traits/cloths/common/4.png',
      url + '/traits/cloths/common/5.png',
      url + '/traits/cloths/common/6.png',
      url + '/traits/cloths/common/7.png',
      url + '/traits/cloths/common/8.png',
      url + '/traits/cloths/common/9.png',
      url + '/traits/cloths/common/10.png',
      url + '/traits/cloths/common/11.png',
      url + '/traits/cloths/common/12.png',
      url + '/traits/cloths/common/13.png',
      url + '/traits/cloths/common/14.png',
      url + '/traits/cloths/common/15.png',
      url + '/traits/cloths/common/16.png',
      url + '/traits/cloths/common/17.png',
      url + '/traits/cloths/common/18.png',
    ],
    "uncommon": [
      url + '/traits/cloths/uncommon/19.png',
      url + '/traits/cloths/uncommon/20.png',
      url + '/traits/cloths/uncommon/21.png',
      url + '/traits/cloths/uncommon/22.png',
      url + '/traits/cloths/uncommon/23.png',
      url + '/traits/cloths/uncommon/24.png',
      url + '/traits/cloths/uncommon/25.png',
      url + '/traits/cloths/uncommon/26.png',
      url + '/traits/cloths/uncommon/27.png',
      url + '/traits/cloths/uncommon/28.png',
    ],
    "rare": [
      url + '/traits/cloths/rare/29.png',
      url + '/traits/cloths/rare/30.png',
      url + '/traits/cloths/rare/31.png',
      url + '/traits/cloths/rare/32.png',
      url + '/traits/cloths/rare/33.png',
      url + '/traits/cloths/rare/34.png',
    ],
    "superrare": [
      url + '/traits/cloths/superrare/35.png',
      url + '/traits/cloths/superrare/36.png',
      url + '/traits/cloths/superrare/37.png',
      url + '/traits/cloths/superrare/38.png',
    ],
    "mythic": [
      url + '/traits/cloths/mythic/39.png',
      url + '/traits/cloths/mythic/40.png',
    ],
  },
  "hairs": {
    "common": [
      url + '/traits/hairs/common/1.png',
      url + '/traits/hairs/common/2.png',
      url + '/traits/hairs/common/3.png',
      url + '/traits/hairs/common/4.png',
      url + '/traits/hairs/common/5.png',
      url + '/traits/hairs/common/6.png',
      url + '/traits/hairs/common/7.png',
      url + '/traits/hairs/common/8.png',
      url + '/traits/hairs/common/9.png',
      url + '/traits/hairs/common/10.png',
      url + '/traits/hairs/common/11.png',
      url + '/traits/hairs/common/12.png',
      url + '/traits/hairs/common/13.png',
      url + '/traits/hairs/common/14.png',
      url + '/traits/hairs/common/15.png',
      url + '/traits/hairs/common/16.png',
      url + '/traits/hairs/common/17.png',
      url + '/traits/hairs/common/18.png',
      url + '/traits/hairs/common/19.png',
      url + '/traits/hairs/common/20.png',
      url + '/traits/hairs/common/21.png',
      url + '/traits/hairs/common/22.png',
      url + '/traits/hairs/common/23.png',
      url + '/traits/hairs/common/24.png',
      url + '/traits/hairs/common/25.png',
      url + '/traits/hairs/common/26.png',
      url + '/traits/hairs/common/27.png',
      url + '/traits/hairs/common/28.png',
    ],
    "uncommon": [
      url + '/traits/hairs/uncommon/29.png',
      url + '/traits/hairs/uncommon/30.png',
      url + '/traits/hairs/uncommon/31.png',
      url + '/traits/hairs/uncommon/32.png',
      url + '/traits/hairs/uncommon/33.png',
      url + '/traits/hairs/uncommon/34.png',
      url + '/traits/hairs/uncommon/35.png',
      url + '/traits/hairs/uncommon/36.png',
      url + '/traits/hairs/uncommon/37.png',
      url + '/traits/hairs/uncommon/38.png',
      url + '/traits/hairs/uncommon/39.png',
      url + '/traits/hairs/uncommon/40.png',
      url + '/traits/hairs/uncommon/41.png',
    ],
    "rare": [
      url + '/traits/hairs/rare/42.png',
      url + '/traits/hairs/rare/43.png',
      url + '/traits/hairs/rare/44.png',
      url + '/traits/hairs/rare/45.png',
      url + '/traits/hairs/rare/46.png',
      url + '/traits/hairs/rare/47.png',
      url + '/traits/hairs/rare/48.png',
      url + '/traits/hairs/rare/49.png',
      url + '/traits/hairs/rare/50.png',
      url + '/traits/hairs/rare/51.png',
    ],
    "superrare": [
      url + '/traits/hairs/superrare/52.png',
      url + '/traits/hairs/superrare/53.png',
      url + '/traits/hairs/superrare/54.png',
      url + '/traits/hairs/superrare/55.png',
      url + '/traits/hairs/superrare/56.png',
      url + '/traits/hairs/superrare/57.png',
      url + '/traits/hairs/superrare/58.png',
    ],
    "mythic": [
      url + '/traits/hairs/mythic/59.png',
      url + '/traits/hairs/mythic/60.png',
      url + '/traits/hairs/mythic/61.png',
      url + '/traits/hairs/mythic/62.png',
      url + '/traits/hairs/mythic/63.png',
    ],
  },
  "weapons": {
    "common": [
      url + '/traits/weapons/common/1.png',
      url + '/traits/weapons/common/2.png',
      url + '/traits/weapons/common/3.png',
      url + '/traits/weapons/common/4.png',
      url + '/traits/weapons/common/5.png',
      url + '/traits/weapons/common/6.png',
      url + '/traits/weapons/common/7.png',
      url + '/traits/weapons/common/8.png',
      url + '/traits/weapons/common/9.png',
      url + '/traits/weapons/common/10.png',
      url + '/traits/weapons/common/11.png',
      url + '/traits/weapons/common/12.png',
      url + '/traits/weapons/common/13.png',
      url + '/traits/weapons/common/14.png',
      url + '/traits/weapons/common/15.png',
      url + '/traits/weapons/common/16.png',
      url + '/traits/weapons/common/17.png',
      url + '/traits/weapons/common/18.png',
    ],
    "uncommon": [
      url + '/traits/weapons/uncommon/19.png',
      url + '/traits/weapons/uncommon/20.png',
      url + '/traits/weapons/uncommon/21.png',
      url + '/traits/weapons/uncommon/22.png',
      url + '/traits/weapons/uncommon/23.png',
      url + '/traits/weapons/uncommon/24.png',
      url + '/traits/weapons/uncommon/25.png',
      url + '/traits/weapons/uncommon/26.png',
      url + '/traits/weapons/uncommon/27.png',
    ],
    "rare": [
      url + '/traits/weapons/rare/28.png',
      url + '/traits/weapons/rare/29.png',
      url + '/traits/weapons/rare/30.png',
      url + '/traits/weapons/rare/31.png',
      url + '/traits/weapons/rare/32.png',
      url + '/traits/weapons/rare/33.png',
    ],
    "superrare": [
      url + '/traits/weapons/superrare/34.png',
      url + '/traits/weapons/superrare/35.png',
      url + '/traits/weapons/superrare/36.png',
      url + '/traits/weapons/superrare/37.png',
      url + '/traits/weapons/superrare/38.png',
    ],
    "mythic": [
      url + '/traits/weapons/mythic/39.png',
      url + '/traits/weapons/mythic/40.png',
      url + '/traits/weapons/mythic/41.png',
    ],
  },
  "pets": {
    "common": [
      url + '/traits/pets/common/1.png',
      url + '/traits/pets/common/2.png',
      url + '/traits/pets/common/3.png',
      url + '/traits/pets/common/4.png',
      url + '/traits/pets/common/5.png',
      url + '/traits/pets/common/6.png',
      url + '/traits/pets/common/7.png',
      url + '/traits/pets/common/8.png',
      url + '/traits/pets/common/9.png',
      url + '/traits/pets/common/10.png',
      url + '/traits/pets/common/11.png',
      url + '/traits/pets/common/12.png',
      url + '/traits/pets/common/13.png',
      url + '/traits/pets/common/14.png',
      url + '/traits/pets/common/15.png',
    ],
    "uncommon": [
      url + '/traits/pets/uncommon/16.png',
      url + '/traits/pets/uncommon/17.png',
      url + '/traits/pets/uncommon/18.png',
      url + '/traits/pets/uncommon/19.png',
      url + '/traits/pets/uncommon/20.png',
      url + '/traits/pets/uncommon/21.png',
      url + '/traits/pets/uncommon/22.png',
    ],
    "rare": [
      url + '/traits/pets/rare/23.png',
      url + '/traits/pets/rare/24.png',
      url + '/traits/pets/rare/25.png',
    ],
    "superrare": [
      url + '/traits/pets/superrare/26.png',
      url + '/traits/pets/superrare/27.png',
    ],
    "mythic": [
      url + '/traits/weapons/mythic/28.png',
    ],
  },
  "background": {
    "common": [
      url + '/traits/backgrounds/common/1.jpg',
      url + '/traits/backgrounds/common/2.jpg',
      url + '/traits/backgrounds/common/3.jpg',
      url + '/traits/backgrounds/common/4.jpg',
      url + '/traits/backgrounds/common/5.jpg',
      url + '/traits/backgrounds/common/6.jpg',
      url + '/traits/backgrounds/common/7.jpg',
    ],
    "uncommon": [
      url + '/traits/backgrounds/uncommon/8.jpg',
      url + '/traits/backgrounds/uncommon/9.jpg',
      url + '/traits/backgrounds/uncommon/10.jpg',
      url + '/traits/backgrounds/uncommon/11.jpg',
      url + '/traits/backgrounds/uncommon/12.jpg',
    ],
    "rare": [
      url + '/traits/backgrounds/rare/13.jpg',
      url + '/traits/backgrounds/rare/14.jpg',
    ],
    "superrare": [
      url + '/traits/backgrounds/superrare/15.jpg',
    ],
    "mythic": [
      url + '/traits/backgrounds/mythic/16.jpg',
    ],
  },
};
